<div class="media profile-left">
    <a class="pull-left profile-thumb" href="<?php echo $this->url('mot/profile');?>">
        <img class="img-circle" src="<?php echo $this->basePath(). "/assets/webarch/img/profiles/avatar.jpg";?>" >
    </a>
    <div class="media-body">
        <h4 class="media-heading">&nbsp;&nbsp;Nickname</h4>
        <small class="text-muted">&nbsp;&nbsp;Executive Assistant</small>
    </div>
</div>
<h5 class="leftpanel-title">Navigation</h5>
<?php 
    echo $this->navigation("sidebar")->menu()->setPartial("template/navigation/sidebar");
?>
<!--<div class="page-sidebar" id="main-menu">
    <div class="page-sidebar-wrapper" id="main-menu-wrapper">
        <div class="user-info-wrapper">
            <div class="profile-wrapper"> 
                <img 
                    src="<?php echo $this->basePath(). "/assets/webarch/img/profiles/avatar.jpg";?>"
                    alt="" data-src="<?php echo $this->basePath(). "/assets/webarch/img/profiles/avatar.jpg";?>"
                    data-src-retina="<?php echo $this->basePath(). "/assets/webarch/img/profiles/avatar2x.jpg";?>" 
                    width="69" height="69" /> 
            </div>
            <div class="user-info">
                <div class="greeting">LastName</div>
                <div class="username">Nick Name</div>
                <div class="status"><a href="<?php echo $this->url('mot/profile');?>"><i class="fa fa-info-circle">&nbsp;View Profile</i></a></div>
            </div>
            <div class="divider"></div>
        </div>
        
        <div class="clearfix"></div>
    </div>
</div>-->