<div class="media profile-left">
    <a class="pull-left profile-thumb" 
       href="<?php echo $this->url('mot/profile');?>">
        <img class="img-circle" 
             src="<?php //echo $this->zfcUserIdentity()->getAvatar();?>" 
        >
    </a>
    <div class="media-body">
        <h4 class="media-heading">
            <a href="<?php echo $this->url('mot/profile'); ?>">
            &nbsp;&nbsp;<?php echo $this->zfcUserIdentity()->getUsername(); ?>
            </a>
        </h4>
        <small class="text-muted">
            &nbsp;&nbsp;<?php //echo $this->zfcUserIdentity()->getPosition();?>
        </small>
    </div>
</div>
<h5 class="leftpanel-title">Navigation</h5>
<?php
    echo $this->navigation("sidebar")
        ->menu()
        ->setPartial("template/navigation/sidebar");
?>