<div class="header navbar navbar-inverse ">
    <div class="navbar-inner">
        <div class="header-seperation">
            <a href="<?php echo $this->url('mot'); ?>"><img src="<?php echo $this->basePath(). "/assets/megamitch-mot/img/mot-logo.png";?>" class="logo" alt=""  data-src="<?php echo $this->basePath(). "/assets/megamitch-mot/img/mot-logo.png";?>" data-src-retina="<?php echo $this->basePath(). "/assets/megamitch-mot/img/mot-logo.png";?>" width="121" height="20"/></a>
          <ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
              <li class="dropdown">
                  <a id="main-menu-toggle" href="#main-menu"  class="" >
                      <div class="iconset top-menu-toggle-white"></div>
                  </a> 
              </li>
          </ul>
        </div>
        <div class="header-quick-nav" >
            <div class="pull-left">
                <ul class="nav quick-section">
                  <li class="quicklinks"> <a href="#" class="" id="layout-condensed-toggle" >
                    <div class="iconset top-menu-toggle-dark"></div>
                    </a> </li>
                </ul>
                <ul class="nav quick-section">
                    <li class="quicklinks"> 
                        <a href="<?php echo $this->url('mot'); ?>" class="" ><i class="fa fa-home fa-lg">&nbsp;Dashboard</i></a> 
                    </li>
<!--                    <li class="quicklinks"> <span class="h-seperate"></span></li>
                    <li class="quicklinks">
                        <a href="#" target="__blank">
                            <i class="fa fa-info-circle fa-2x">&nbsp;&nbsp;Notification</i>
                        </a>
                    </li>
                    <li class="quicklinks"> <span class="h-seperate"></span></li>-->
                </ul>
            </div>
            <div class="pull-right">
              <div class="chat-toggler">
                <div class="user-details">
                    <div class="">
                        <a href="<?php // echo $this->url("zfcuser/logout"); ?>"> <i class="fa fa-power-off">&nbsp;&nbsp;Logout</i></a>
                    </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

    
      
      
      
      