<?php 
    /**
     * DO NOT CHANGE CURRENT PATH SETTINGS IF NOT FAMILIAR
     */
    $path = $this->basePath();
?>

<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>
        <?php echo $this->headTitle('Mega Mitch Office Tool')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php echo $this->headLink(
                    [
                        'rel' => 'shortcut icon',
                        'href' => $path . '/img/favicon.ico'
                    ]
                )
            ->prependStylesheet(
                $path . '/assets/bootstrap/css/bootstrap-theme.min.css'
            )
            ->prependStylesheet(
                $path . '/assets/bootstrap/css/bootstrap.min.css'
            )
        ?>
    </head>
    <body>
        <div class="container text-center" 
             style="padding: auto; margin: auto; display: block;">
            <?php echo $this->content; ?>
        </div>
        
        <?php echo $this->inlineScript()
            ->prependFile($path . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($path . '/assets/jquery/jquery.min.js');
        ?>
    </body>
</html>
