<!-- 
/**
* The MIT License
*
* Copyright (c) 2012-2014, contributors of Mega Mitch Credit, Inc. software project.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
-->

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">        
        <?php echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');
        ?>
        <?php echo $this->headTitle('Mega Mitch Credit, Inc.')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath() . '/assets/webarch/css/magic_space.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/css/custom-icon-set.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/css/responsive.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/css/style.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/css/animate.min.css')
            ->prependStylesheet($this->basePath() . '/assets/font-awesome-4.2.0/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap-3.2.0/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/assets/bootstrap-3.2.0/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/jquery-isotope/isotope.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/jquery-ricksaw-chart/css/rickshaw.css',"screen")
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/jquery-slider/css/jquery.sidr.light.css',"screen")
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/pace/pace-theme-flash.css',"screen")
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/owl-carousel/owl.carousel.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/shape-hover/css/component.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/shape-hover/css/demo.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/jquery-metrojs/MetroJs.css')
            ->prependStylesheet($this->basePath() . '/assets/webarch/plugins/jquery-polymaps/style.css', "screen");
        ?>
    </head>
    <body>
        <?php echo $this->partial('partial/navigation/header'); ?>
        <div class="page-container row-fluid">
            <?php echo $this->partial('partial/navigation/sidebar'); ?>
            <div class="page-content">
                <div class="content">
                    <div class="container-fluid">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                <div class="container-fluid">
                    <?php echo $this->partial('template/footer'); ?>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript()                               
            ->prependFile($this->basePath() . '/assets/webarch/js/demo.js')
            ->prependFile($this->basePath() . '/assets/webarch/js/chat.js')
            ->prependFile($this->basePath() . '/assets/webarch/js/core.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-slider/jquery.sidr.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery.cookie.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-lazyload/jquery.lazyload.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-block-ui/jqueryblockui.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-unveil/jquery.unveil.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/breakpoints.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')
            ->prependFile($this->basePath() . '/assets/webarch/plugins/jquery-1.8.3.min.js');
        ?>
    </body>
</html>
