<?php 
    /**
     * DO NOT CHANGE CURRENT PATH SETTINGS IF NOT FAMILIAR
     */
    $path = $this->basePath();
?>

<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendName(
                    'viewport',
                    'width=device-width, initial-scale=1.0'
                );
        ?>
        <?php echo $this->headTitle('Mega Mitch Office Tool')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
        ?>
        <?php 
            echo $this->headLink(
                        [
                            'rel' => 'shortcut icon',
                            'href' => $path . '/img/favicon.ico'
                        ]
                )
            ->prependStylesheet($path . '/assets/mot/css/style.override.css')
            ->prependStylesheet($path . '/assets/mot/css/style.default.css')
            ->prependStylesheet(
                $path . '/assets/font-awesome/css/font-awesome.css'
            )
            ->prependStylesheet(
                $path . '/assets/bootstrap/css/bootstrap-theme.min.css'
            )
            ->prependStylesheet(
                $path . '/assets/bootstrap/css/bootstrap.min.css'
            )
        ?>
    </head>
    <body>
        <header>
             <?php echo $this->partial('partial/navigation/header'); ?>
        </header>
        <section>
            <div class="mainwrapper">
                <div class="leftpanel">
                    <?php 
                        if($this->zfcUserIdentity()) {
                            echo $this->partial('partial/navigation/sidebar');  
                        }                        
                    ?>
                </div>
                <div class="mainpanel">
                    <?php echo $this->content; ?>
                </div>                
            </div>
        </section>       
        <?php echo $this->inlineScript()           
            ->prependFile($path . '/assets/mot/js/custom.js')
            ->prependFile($path . '/assets/mot/js/holder.js')
            ->prependFile($path . '/assets/bootstrap/js/tab.js')
            ->prependFile($path . '/assets/bootstrap/js/tooltip.js')
            ->prependFile($path . '/assets/bootstrap/js/popover.js')
            ->prependFile($path . '/assets/bootstrap/js/bootstrap.min.js')
            ->prependFile($path . '/assets/jquery/jquery.min.js');
        ?>
    </body>
</html>
