
<div class="row">
    <div class="col-lg-8">
        <h1> All employees <small> (total active accounts) </small></h1> 
        
    </div>
    <div class="col-lg-4">
        <input class="navbar-search" type="text" data-bind=""/>
<!--        <div class="navbar-search"> 
            
        </div>-->
    </div>
</div>
<hr>
<div class="row">
    <div class="col-lg-12 col-md-12">
        <p>sample</p>
    </div>
</div>
