<div class="row">
    <div class="col-lg-3 col-md-6">
        <img class="img-circle image-responsive center-block" 
                 width="180" height="180" 
                 src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"
        />
        <h4 class="text-center">
            <strong>Taojo</strong>, Josephine Dalangin
            <br>
            <small>Executive Assistant</small>
        </h4>
        <div class="panel panel-success">
            <div class="panel-heading">
                <h6 class="panel-title"><strong>Mega Mitch Personnel Info:</strong></h6>
            </div>
            <div class="panel-body">
                <span><i class="fa fa-barcode"></i>&nbsp;:&nbsp;01-0037</span> <br>
                <span><i class="fa fa-envelope-o"></i>&nbsp;:&nbsp;josephine.taojo@megamitch.com</span> <br>
                <span><i class="fa fa-calendar"></i>&nbsp;:&nbsp;2014-04-11</span> <br>
                <span><i class="fa fa-mobile fa-2x"></i>&nbsp;:&nbsp;0917-505-8928</span>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-6">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h4>
                    <strong>Personal Information:</strong>
                </h4>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-birthday-cake"></i></span>
                    <input type="text" class="form-control" placeholder="1988-01-01"/>
                    <span class="input-group-addon"><i class="fa fa-mobile"></i></span>
                    <input type="text" class="form-control" placeholder="0917-505-8928"/>
                    <span class="input-group-addon"><i class="fa fa-heart"></i></span>
                    <input type="text" class="form-control" placeholder="A+"/>
                </div>
                <div class="input-group">
                     <span class="input-group-addon"><i class="fa fa-home"></i></span>
                    <input type="text" class="form-control" placeholder="Zone Orchids Suarez Iligan City"/>
                </div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                    <input type="text" class="form-control" placeholder="jtaojo@gmail.com"/>
                </div>
                <br>
                <h4>
                    <strong>For Emergency</strong> <small>please contact:</small>
                </h4>
                <div class="input-group input-group-sm">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <input type="text" class="form-control" placeholder="Josephine Taojo"/>
                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                    <input type="text" class="form-control" placeholder="0916-493-4483"/>
                </div>
                <div class="input-group  input-group-sm">
                    <span class="input-group-addon"><i class="fa fa-home"></i></span>
                    <input type="text" class="form-control" placeholder="Zone Orchids Suarez Iligan City"/>
                </div>

            </div>
            <div class="col-md-6 col-sm-6">
                <h4>
                    <strong>Government Issued Identification:</strong>
                </h4>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                    <input type="text" id="tin" class="form-control" placeholder="TIN: 289-975-14000"/>
                    <input type="text" id="sss" class="form-control" placeholder="SSS: 08-1750705-5"/>
                    <input type="text" id="pagibig" class="form-control" placeholder="Pag-ibig: 1211-1022-2292"/>
                    <input type="text" id="philhealth" class="form-control" placeholder="PhilHealth: 15-025334681-9"/>
                </div>
            </div>
        </div>
        <div class="divider"><br></div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12">
                <p>
                    Cras ultrices magna tristique, fringilla elit quis, condimentum neque. Etiam sagittis rutrum erat quis aliquam. Aenean in nulla quis quam tristique volutpat a sed felis. Nulla sollicitudin, lectus sed accumsan vehicula, eros magna viverra quam, eget imperdiet lacus sem nec lacus. Proin semper congue lacus, id consequat ex fringilla in. Praesent facilisis mi nec egestas efficitur. Cras sit amet felis mauris. Aenean luctus, eros in finibus aliquet, urna tortor viverra leo, sed ultricies ante quam quis mi. Sed purus ante, ultrices in tincidunt vitae, lobortis sit amet erat.
                </p>
            </div>
        </div>
    </div>
</div>