<div class="row">
    <div class="col-lg-12 page-header">
        <div class="col-md-6">
            <h1 > All employees <small> ($total active accounts) </small></h1>
        </div>
        <div class="col-md-6">
            <input type="text" />
        </div>
    </div>
    
    <?php // if($this->zfcUserIdentity()): ?>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Alcantara</strong>, Chantrelle
                </a>
                <br> 
                <small>Teller</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i>
                <br>
                <i class="fa fa-envelope">&nbsp;chantrelle.alcantara@megamitch.com</i>

            </span>
            <div class="divider"><br></div>
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Taojo</strong>, Josephine Dalangin
                </a>
                <br>
                <small>Executive Assistant</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;josephinedalanging.taojo@megamitch.com</i>
            </span>
            <div class="divider"><br></div>
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Hingco</strong>, Rizel Mae
                </a>
                <br>
                <small>Teller</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;rizelmae.hingco@megamitch.com</i>
            </span>
            <div class="divider"><br></div class="divider">
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Alavanza</strong>, Ella Mae Amor
                </a>
                <br> 
                <small>Junior Credit Officer</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;ellamaeamor.alavanza@megamitch.com</i>
            </span>
            <div class="divider"><br></div>
        </div>

        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Alcantara</strong>, Chantrelle
                </a>
                <br>
                <small>Teller</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;chantrelle.alcantara@megamitch.com</i>
            </span>
            <div class="divider"><br></div>
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Taojo</strong>, Josephine Dalangin
                </a>
                <br>
                <small>Executive Assistant</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;josephinedalanging.taojo@megamitch.com</i>
            </span>
            <div class="divider"><br></div>
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Hingco</strong>, Rizel Mae
                </a>
                <br> 
                <small>Teller</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;rizelmae.hingco@megamitch.com</i>
            </span>
            <div class="divider"><br></div class="divider">
        </div>
        <div class="col-lg-3 col-sm-3 text-center">
            <img class="img-circle image-responsive center-block" width="180" height="180" src="<?php echo $this->basePath(). "/assets/webarch/img/profile-pic-big.png";?>"/>
            <h4>
                <a href="<?php echo $this->url('mot/profile', []); ?>">
                    <strong>Alavanza</strong>, Ella Mae Amor
                </a>
                <br> 
                <small>Junior Credit Officer</small>
            </h4>
            <span class="text-extra-small">
                <i class="fa fa-phone-square">&nbsp;09170000001</i> <br>
                <i class="fa fa-envelope">&nbsp;ellamaeamor.alavanza@megamitch.com</i>
            </span>
            <div class="divider"><br></div>
        </div>
    <?php // endif; ?>
</div>
